"""Create Audit Table

Revision ID: 368fef4499c7
Revises: 4d14362aa144
Create Date: 2026-07-09 16:47:10.439777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368fef4499c7'
down_revision = '4d14362aa144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audits')
    # ### end Alembic commands ###
