"""Add azure_version_id to versions

Revision ID: 7eaa7c28f07d
Revises: 368fef4499c7
Create Date: 2026-07-09 21:21:08.048791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaa7c28f07d'
down_revision = '368fef4499c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_version_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_column('azure_version_id')

    # ### end Alembic commands ###
